services:
  clickhouse-keeper1:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-keeper1
    command: /usr/bin/clickhouse-keeper --config-file=/etc/clickhouse-server/config.xml
    volumes:
      - ../clickhouse/clickhouse_keeper/keeper1-config.xml:/etc/clickhouse-server/config.xml
      - clickhouse_keeper1_data:/var/lib/clickhouse

    networks:
      clickhouse-keeper-network:
        aliases:
          - clickhouse-keeper1
    deploy:
      replicas: 1
      # placement:
      #   constraints: [node.labels.main == true]
      restart_policy:
          condition: on-failure

  clickhouse-keeper2:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-keeper2
    command: /usr/bin/clickhouse-keeper --config-file=/etc/clickhouse-server/config.xml
    volumes:
      - ../clickhouse/clickhouse_keeper/keeper2-config.xml:/etc/clickhouse-server/config.xml
      - clickhouse_keeper2_data:/var/lib/clickhouse
    networks:
      clickhouse-keeper-network:
        aliases:
          - clickhouse-keeper2
    deploy:
      replicas: 1
      # placement:
      #   constraints: [node.labels.main == true]
      restart_policy:
          condition: on-failure

  clickhouse-keeper3:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-keeper3
    command: /usr/bin/clickhouse-keeper --config-file=/etc/clickhouse-server/config.xml
    volumes:
      - ../clickhouse/clickhouse_keeper/keeper3-config.xml:/etc/clickhouse-server/config.xml
      - clickhouse_keeper3_data:/var/lib/clickhouse
    networks:
      clickhouse-keeper-network:
        aliases:
          - clickhouse-keeper3
    deploy:
      replicas: 1
      # placement:
      #   constraints: [node.labels.main == true]
      restart_policy:
          condition: on-failure

  clickhouse-server1:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server1
    volumes:
      - ../clickhouse/node1-config/:/etc/clickhouse-server/config.d/
      - ../clickhouse/node-entrypoints/main:/docker-entrypoint-initdb.d
      - ../preprocessing/geoip.csv:/var/lib/clickhouse/user_files/csv/ip_region_map.csv
      - ../preprocessing/geoip_cc.csv:/var/lib/clickhouse/user_files/csv/ip_region_cc_map.csv
      - clickhouse_server1_data:/var/lib/clickhouse
      - clickhouse_server1_TTL:/clickhouse_data/server1
    networks:
      clickhouse-server-network:
        aliases:
          - clickhouse-server1
      clickhouse-keeper-network:
        aliases:
          - clickhouse-server1
      data-network:
        aliases:
          - clickhouse-server1
    deploy:
      replicas: 1
      # placement:
      #   constraints: [node.labels.main == true]
      restart_policy:
          condition: on-failure
      update_config:
        delay: 10s
      resources:
        limits:
          cpus: "0.50"
          memory: 1200M
    depends_on:
      - clickhouse-keeper1
      - clickhouse-keeper2
      - clickhouse-keeper3
      - data-streamer
    ports:
      - "9001:9000" # Native client port
      - "8123:8123" # HTTP interface

  clickhouse-server2:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server2
    volumes:
      - ../clickhouse/node2-config/:/etc/clickhouse-server/config.d/
      - ../clickhouse/node-entrypoints/common:/docker-entrypoint-initdb.d
      - clickhouse_server2_data:/var/lib/clickhouse
      - clickhouse_server2_TTL:/clickhouse_data/server2
    networks:
      clickhouse-server-network:
        aliases:
          - clickhouse-server2
      clickhouse-keeper-network:
        aliases:
          - clickhouse-server2
    deploy:
      replicas: 1
      # placement:
      #   constraints: [node.labels.main == true]
      restart_policy:
          condition: on-failure
      update_config:
        delay: 10s
      resources:
        limits:
          cpus: "0.50"
          memory: 1200M
    depends_on:
      - clickhouse-keeper1
      - clickhouse-keeper2
      - clickhouse-keeper3
    ports:
      - "9002:9000" # Native client port
      - "8124:8123" # HTTP interface

networks:
  clickhouse-server-network:
    driver: overlay
    attachable: true
  clickhouse-keeper-network:
    driver: overlay
    attachable: true

volumes:
  clickhouse_server1_data:
    driver: local
  clickhouse_server2_data:
    driver: local
  clickhouse_keeper1_data:
    driver: local
  clickhouse_keeper2_data:
    driver: local
  clickhouse_keeper3_data:
    driver: local
  clickhouse_server1_TTL:
    driver: local
  clickhouse_server2_TTL:
    driver: local
