services:
  clickhouse-keeper1:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-keeper1
    command: >
      /usr/bin/clickhouse-keeper --config-file=/etc/clickhouse-server/config.xml
    volumes:
      - ./clickhouse_keeper/keeper1-config.xml:/etc/clickhouse-server/config.xml
      - clickhouse_keeper1_data:/var/lib/clickhouse

    networks:
      clickhouse-keeper-network:
        aliases:
          - clickhouse-keeper1

  clickhouse-keeper2:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-keeper2
    command: >
      /usr/bin/clickhouse-keeper --config-file=/etc/clickhouse-server/config.xml
    volumes:
      - ./clickhouse_keeper/keeper2-config.xml:/etc/clickhouse-server/config.xml
      - clickhouse_keeper2_data:/var/lib/clickhouse
    networks:
      clickhouse-keeper-network:
        aliases:
          - clickhouse-keeper2

  clickhouse-keeper3:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-keeper3
    command: >
      /usr/bin/clickhouse-keeper --config-file=/etc/clickhouse-server/config.xml
    volumes:
      - ./clickhouse_keeper/keeper3-config.xml:/etc/clickhouse-server/config.xml
      - clickhouse_keeper3_data:/var/lib/clickhouse
    networks:
      clickhouse-keeper-network:
        aliases:
          - clickhouse-keeper3

  clickhouse-server1:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server1
    volumes:
      - ./node1-config/:/etc/clickhouse-server/config.d/
      - clickhouse_server1_data:/var/lib/clickhouse
      - clickhouse_server1_TTL:/clickhouse_data/server1
    networks:
      clickhouse-server-network:
        aliases:
          - clickhouse-server1
      clickhouse-keeper-network:
        aliases:
          - clickhouse-server1
    deploy:
      replicas: 1
      # placement:
      #   constraints: [node.labels.role == server]
      update_config:
        delay: 10s
      resources:
        limits:
          cpus: "0.50"
          memory: 1200M
    depends_on:
      - clickhouse-keeper1
      - clickhouse-keeper2
      - clickhouse-keeper3
    ports:
      - "9001:9000"  # Native client port
      - "8123:8123"  # HTTP interface

  clickhouse-server2:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse-server2
    volumes:
      - ./node2-config/:/etc/clickhouse-server/config.d/
      - clickhouse_server2_data:/var/lib/clickhouse
      - clickhouse_server2_TTL:/clickhouse_data/server2
    networks:
      clickhouse-server-network:
        aliases:
          - clickhouse-server2
      clickhouse-keeper-network:
        aliases:
          - clickhouse-server2
    deploy:
      replicas: 1
      # placement:
      #   constraints: [node.labels.role == server]
      update_config:
        delay: 10s
      resources:
        limits:
          cpus: "0.50"
          memory: 1200M
    depends_on:
      - clickhouse-keeper1
      - clickhouse-keeper2
      - clickhouse-keeper3
    ports:
      - "9002:9000"  # Native client port
      - "8124:8123"  # HTTP interface

networks:
  clickhouse-server-network:
    driver: overlay
    attachable: true
  clickhouse-keeper-network:
    driver: overlay
    attachable: true

volumes:
  clickhouse_server1_data:
    driver: local
  clickhouse_server2_data:
    driver: local
  clickhouse_keeper1_data:
    driver: local
  clickhouse_keeper2_data:
    driver: local
  clickhouse_keeper3_data:
    driver: local
  clickhouse_server1_TTL:
    driver: local
  clickhouse_server2_TTL:
    driver: local