{
 "title": "Internet traffic capture analysis",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Top ports (by bandwidth)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT Port,\r\n  src_bw/1024.0/1024.0 AS \"Source Port Bandwidth (MB)\",\r\n  dst_bw/1024.0/1024.0 AS \"Destination Port Bandwidth (MB)\"\r\nFROM (\r\n    SELECT src_port AS Port,\r\n      SUM(pkt_len) AS src_bw\r\n    FROM traffic_records_all\r\n    GROUP BY src_port\r\n    ORDER BY src_bw DESC\r\n    LIMIT 40\r\n  ) AS src\r\n  INNER JOIN (\r\n    SELECT dst_port AS Port,\r\n      SUM(pkt_len) AS dst_bw\r\n    FROM traffic_records_all\r\n    GROUP BY dst_port\r\n    ORDER BY dst_bw DESC\r\n    LIMIT 40\r\n  ) AS dst USING (Port)\r\nORDER BY (src_bw + dst_bw) DESC\r\nLIMIT 40;"
    }
   ]
  },
  {
   "title": "Distribution of L4 protocol",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  l4_protocol as Protocol,\r\n  COUNT(Protocol) as ProtocolCount\r\n  FROM traffic_records_all\r\n  GROUP BY Protocol"
    }
   ]
  },
  {
   "title": "Top ports (by count)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \r\n    Port, \r\n    SourcePortCount, \r\n    DestPortCount\r\nFROM\r\n(\r\n    SELECT \r\n        src_port AS Port, \r\n        COUNT(*) AS SourcePortCount\r\n    FROM traffic_records_all\r\n    GROUP BY src_port\r\n    ORDER BY SourcePortCount DESC\r\n    LIMIT 40\r\n) AS src\r\nINNER JOIN\r\n(\r\n    SELECT \r\n        dst_port AS Port, \r\n        COUNT(*) AS DestPortCount\r\n    FROM traffic_records_all\r\n    GROUP BY dst_port\r\n    ORDER BY DestPortCount DESC\r\n    LIMIT 40\r\n) AS dst\r\nUSING (Port)\r\nORDER BY (SourcePortCount + DestPortCount) DESC\r\nLIMIT 40;\r\n"
    }
   ]
  },
  {
   "title": "Top 10 source ports (by count)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  src_port as SourcePort,\r\n  COUNT(SourcePort) as SourcePortCount\r\n  FROM traffic_records_all\r\n  GROUP BY SourcePort\r\n  ORDER BY SourcePortCount DESC\r\n  LIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 destination ports (by count)",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  dst_port as DestPort,\r\n  COUNT(DestPort) as DestPortCount\r\n  FROM traffic_records_all\r\n  GROUP BY DestPort\r\n  ORDER BY DestPortCount DESC\r\n  LIMIT 10"
    }
   ]
  }
 ]
}