services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - ../ui/grafana_clickhouse_datasource.yaml:/etc/grafana/provisioning/datasources/clickhouse.yaml:ro
      - ../ui/grafana_dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana_dashboards.yaml:ro
      - ../ui/dashboard_1.json:/var/lib/grafana/dashboards/dashboard_1.json
    networks:
      outside_net:
        aliases:
          - grafana
      clickhouse-server-network:
        aliases:
          - grafana
    deploy:
      replicas: 1
      # placement:
      #   constraints: [node.labels.worker == true]
      restart_policy:
        condition: on-failure
    depends_on:
      - clickhouse-server1
    environment:
      - GF_INSTALL_PLUGINS=grafana-clickhouse-datasource
      - GF_SECURITY_ADMIN_USER=thewebfarm
      - GF_SECURITY_ADMIN_PASSWORD=mrafbeweht
    ports:
      - "7602:3000"

networks:
  outside_net:
    attachable: true

volumes:
  grafana-storage:
    driver: local
